#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Accepts 4 parameters
#   The path to the file to be transferred
#   The IP of the server we want to transfer the file to
#   The username scp connects with
#   The path to the SSH private key that scp uses

FILEPATH=$1
IP_ADDRESS=$2
USERNAME=$3
PRIVATE_KEY=$4

if [ $# -eq 4 ]
then
  scp -o StrictHostKeyChecking=no -i "$PRIVATE_KEY" "$FILEPATH" "$USERNAME@$IP_ADDRESS:~/"
else
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi